---

- name: create folder for custom assets
  file:
    path: /usr/local/share/jitsi-meet
    state: directory
    owner: root
    group: root
    mode: a=rx

- name: copy custom assets
  copy:
    src: "{{ jitsi_meet_custom_assets_folder }}/"
    dest: /usr/local/share/jitsi-meet/
    owner: root
    group: root
    mode: a=r
  when: jitsi_meet_custom_assets_folder is defined

- name: include css files in html head
  lineinfile:
    path: /usr/local/share/jitsi-meet/plugin.head.html
    line: <link rel="stylesheet" href="/css/{{ item | basename }}">
    create: yes
    owner: root
    group: root
    mode: a=r
  with_fileglob: "{{ jitsi_meet_custom_assets_folder }}/css/*.css"
  when: jitsi_meet_custom_assets_folder is defined

- name: Application configuration file
  template:
    dest: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-interface_config.js"
    src: interface_config.js.j2
    owner: root
    group: root
    mode: "0644"

- name: Title configuration file
  template:
    src: title.html.j2
    dest: "/usr/local/share/jitsi-meet/title.html"
    owner: root
    group: root
    mode: "0644"
