---

- name: Set debconf options for jitsi-meet
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
    - name: jitsi-meet-web-config
      question: jitsi-meet/cert-choice
      value: "{{ jitsi_meet_cert_choice }}"
      vtype: string
    - name: jitsi-meet-web-config
      question: jitsi-meet/cert-path-crt
      value: "{{ jitsi_meet_ssl_cert_path }}"
      vtype: string
    - name: jitsi-meet-web-config
      question: jitsi-meet/cert-path-key
      value: "{{ jitsi_meet_ssl_key_path }}"
      vtype: string
    - name: jitsi-meet-prosody
      question: jitsi-meet-prosody/turn-secret
      value: "{{ jitsi_meet_turn_secret }}"
      vtype: string

- name: Install jitsi-meet
  apt:
    pkg: "{{ jitsi_meet_packages }}"
    install_recommends: no
    state: present

- name: Copy jicofo config
  template:
    src: jicofo/config.j2
    dest: /etc/jitsi/jicofo/config
    owner: jicofo
    group: jitsi
    mode: 0640
  notify: restart jicofo

- name: Copy Jicofo log.properties
  copy:
    content: "{{ jitsi_meet_jicofo_logging_properties }}"
    dest: /etc/jitsi/jicofo/logging.properties
    owner: jicofo
    group: jitsi
    mode: 0640
  notify: restart jicofo

- name: Copy jitsi meet config
  template:
    mode: 0644
    src: meet-config.js.j2
    dest: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"

- name: Enable jicofo
  service:
    name: jicofo
    enabled: yes

- meta: flush_handlers
