---

- name: Ensure that nginx is installed.
  apt:
    name:
      - nginx
      - python3-certbot-nginx
    state: present

- name: Adjust global nginx config.
  template:
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Add mimetype for wasm files.
  lineinfile:
    path: /etc/nginx/mime.types
    line: "    application/wasm                      wasm;"
    insertbefore: '^\}$'
  notify: reload nginx

- name: Copy Nginx config for Jitsi Meet domain.
  template:
    dest: "/etc/nginx/sites-available/{{ jitsi_meet_server_name }}.conf"
    src: nginx/sites-available/vhost.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Ensure Nginx multiplexer config is absent
  file:
    path: "/etc/nginx/modules-enabled/60-jitsi-meet.conf"
    state: absent
  notify: restart nginx

- name: Deactivate default Nginx site.
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Generate dhparam
  shell: "openssl dhparam 1024 > {{ jitsi_meet_nginx_ssl_dhparam }}"
  args:
    creates: "{{ jitsi_meet_nginx_ssl_dhparam }}"
  when: jitsi_meet_nginx_ssl_preset == 'old'
  notify: restart nginx

- name: Copy dhparam
  copy:
    src: "dhparam"
    dest: "{{ jitsi_meet_nginx_ssl_dhparam }}"
    owner: root
    group: root
    mode: "0640"
  when: jitsi_meet_nginx_ssl_preset == 'intermediate'
  notify: restart nginx

- name: Activate custom Jitsi Meet Nginx site.
  file:
    path: "/etc/nginx/sites-enabled/{{ jitsi_meet_server_name }}.conf"
    src: "/etc/nginx/sites-available/{{ jitsi_meet_server_name }}.conf"
    state: link
  notify: reload nginx

- name: Enable nginx
  service:
    name: nginx
    enabled: yes
