---

- name: Copy prosody config
  template:
    src: prosody/prosody.cfg.lua.j2
    dest: "/etc/prosody/prosody.cfg.lua"
    mode: 0640
    owner: root
    group: prosody
    validate: "luac -p %s"
  notify: restart prosody

- name: Copy additional prosody config
  template:
    src: prosody/conf.avail/virtualhost.cfg.lua.j2
    dest: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
    mode: 0644
    owner: root
    group: root
    validate: "luac -p %s"
  notify: restart prosody

- name: Link additional prosody config
  file:
    src: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
    dest: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
    owner: root
    group: root
    state: link
  notify: restart prosody

- name: Generate SSL keypair for Prosody service
  shell: |
    set -o pipefail
    yes '' | prosodyctl cert generate {{ item }}
  args:
    creates: /var/lib/prosody/{{ item }}.crt
    executable: /bin/bash
  register: prosody_cert_gen
  changed_when: prosody_cert_gen.rc and prosody_cert_gen.rc == 141
  failed_when: prosody_cert_gen.rc != 141 and prosody_cert_gen.rc != 0
  loop:
    - "{{ jitsi_meet_server_name }}"
    - "auth.{{ jitsi_meet_server_name }}"
  notify:
    - restart prosody
    - update ca-certificates

- name: Link main SSL certificate to /etc/prosody/certs/
  file:
    src: "/var/lib/prosody/{{ jitsi_meet_server_name }}.{{ item }}"
    dest: "/etc/prosody/certs/{{ jitsi_meet_server_name }}.{{ item }}"
    state: link
  loop:
    - crt
    - key
  notify:
    - restart prosody

- name: Link auth SSL certificate to /etc/prosody/certs/
  file:
    src: "/var/lib/prosody/auth.{{ jitsi_meet_server_name }}.{{ item }}"
    dest: "/etc/prosody/certs/auth.{{ jitsi_meet_server_name }}.{{ item }}"
    state: link
  loop:
    - crt
    - key
  notify:
    - restart prosody

- name: Link auth certificate to trusted store
  file:
    src: "/var/lib/prosody/auth.{{ jitsi_meet_server_name }}.crt"
    dest: "/usr/local/share/ca-certificates/auth.{{ jitsi_meet_server_name }}.crt"
    state: link
  notify:
    - update ca-certificates

- meta: flush_handlers

- name: Register jicofo agent with Prosody service.
  command: prosodyctl register focus auth.{{ jitsi_meet_server_name }} {{ jitsi_meet_jicofo_password }}  # noqa: 301
  changed_when: false

- name: Register jvb agent with Prosody service.
  command: prosodyctl register jvb auth.{{ jitsi_meet_server_name }} {{ jitsi_meet_videobridge_password }}  # noqa: 301
  changed_when: false

- name: Enable prosody
  service:
    name: prosody
    enabled: yes
